package fr.harmonia.tsclientquery.objects;

public enum SpeakIcon {
	IDLE, CHANNEL_COMMANDER, SPEAKING, CHANNEL_COMMANDER_SPEAKING, MICROPHONE_MUTED, MICROPHONE_DISABLED, SPEAKER_MUTED, SPEAKER_DISABLE;
}
